export const QUERY_KEY = {
  ALL_FISH_USER: "all_fishing_user",
  ALL_FISH: "all_fishing",
  PAID: "paid_fishing",
  ALL_FISH_FOR_MAP: "all_fishing_for_map",
  GET_ONE_FISHING: "one_by_id_fishing",
  GET_USER: "get_user",
  LOAD_PHOTO: "load_photo",
  GET_COMMENTS: "get_comments",
  CREATE_COMMENTS: "create_comments",
  DELETE_COMMENTS: "delete_comments",
  POST_GET_ALL_BY_USER: "post_get_all_by_user",
  POST_GET_ALL: "post_get_all",
  POST_GET_ONE: "post_get_one",
  POST_CREATE: "post_create",
  POST_DELETE: "post_delete",
  POST_COMMENTS_GET_ALL_BY_POST: "comment_post_get_all_by_post",
  POST_COMMENTS_CREATE: "comment_post_create",
  POST_COMMENTS_DELETE: "comment_post_delete",
}
